spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope: profile, email
#            redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI}
#            authorization-grant-type: authorization_code
#            client-name: Google
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub
  application:
    name: HoopStretchApi
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 360000 # 1hr in millis
  refresh-expiration: 259200000 # 30 days in millis
  jwt-cookie-secure: true
  jwt-cookie-http-only: true
  jwt-access-token-cookie-path: "/"

cors:
  allowed-origins:
    - http://localhost:8080
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed-headers:
    - Authorization
    - Content-Type
server:
  servlet:
    context-path: /api